<?php

require_once("Event.php");
require_once("Exceptions.php");

/**
 * This class represents the tags generated by a user for a specific item.
 * The user could have generate multiple tags for a item.
 *
 * @param string  $resource_url
 * @param integer $user_id 
 * @param array   $tags         an associative array where the key is the
 *							    dimension and the value the tag.
 */
class Tagging extends Event {

	const COMMAND = 'taggings';
	function __construct( $resource_url, $user_id, $tags) {
		parent::__construct($resource_url, $user_id);

		$taggings = array();
		//Add only tags with tag
		foreach($tags as $tag) {
			if( !empty($tag["value"]) ) {
				if( !$this->isValid($tag["value"]) )
					throw new EncodingException("Invalid tag:". $tag["value"]."for user: $user_id resource: $resource_url");
				
				$taggings[] = array("value" => $tag["value"]); 
			}
		}
		$this->data["tags"] = $taggings;


//		print(json_encode($taggings));
		if ( count($taggings) == 0 )
			throw new TaggingsException("No valid tags for user: $user_id resource: $resource_url");		
	
	}	
	
	function send(){
		parent::send(self::COMMAND);
	}
}
