<?php

require_once("Event.php");
require_once("Exceptions.php");

/**
 * This class represents a review generated by a user for a specific item.
 * The user could have generate only one review per item.
 *
 * @param string  $resource_url
 * @param integer $user_id 
 * @param string  review        the text of the review
 */
class Reviewing extends Event {

	const COMMAND = 'reviewings';	
	function __construct( $resource_url, $user_id, $review ) {
		parent::__construct($resource_url, $user_id);
		
		if( !$this->isValid($review) )
			throw new EncodingException("Invalid review:".$review."for user: $user_id resource: $resource_url" );
		
		$this->data["review"] = $review;
	}

	function send() {
		parent::send(self::COMMAND);
	}
}
